spring.application.name=product_microservice


spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.acks=1

#spring.kafka.producer.retries = 10

#spring.kafka.producer.properties.retry.backoff.ms = 1000



# kafka documentation recommends us to setup the delivery.timeout.ms
# used to configure the time that the producer will wait for a response from all replicas after sending a message and this is actually
#the maximum amount of time producer is allowed to wait until the entire send operation is complete including retry operations
# example f it does not receive ACK from all in sync replicas , it will send an error





spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=30000
