server.port=0
spring.kafka.consumer.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=amount-widthrawal-event
spring.kafka.consumer.properties.spring.json.trusted.packages=com.app.*


# configure the consumer microservice to read messages for committed transactions


spring.kafka.consumer.isolation-level=read_committed
